name:                hw06
version:             0.1.0.0
github:              "MI-AFP/hw06"
license:             MIT
author:              "Marek Suchánek"
maintainer:          "marek.suchanek@fit.cvut.cz"
copyright:           "2023 Marek Suchánek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/MI-AFP/hw08#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- lens
- monad-loops
- mtl

library:
  source-dirs: src

executables:
  traveler:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw06

tests:
  hw06-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw06
    - hspec
