name:                hw04
version:             0.1.0.0
github:              "MI-AFP/hw04"
license:             MIT
author:              "Marek Suchánek"
maintainer:          "marek.suchanek@fit.cvut.cz"
copyright:           "2023 Marek Suchánek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/MI-AFP/hw04#readme>

dependencies:
- base >= 4.7 && < 5
- time
- bytestring
- containers

library:
  source-dirs: src

tests:
  hw04-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw04
    - hspec
